version: '3.8'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "ola1234"
      ACCEPT_EULA: "Y"
    ports:
      - "1434:1433"
  api:
    build: .
    depends_on:
      - sqlserver
    environment:
      ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=AdventureWorks;User Id=Ola_Shawwal;Password=ola1234;"
    ports:
      - "8080:80"
